// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission06_ckearl2.Models;

namespace Mission06_ckearl2.Migrations
{
    [DbContext(typeof(MovieContext))]
    partial class MovieContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Mission06_ckearl2.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryID");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Comedy"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Action"
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "Romance"
                        },
                        new
                        {
                            CategoryID = 4,
                            CategoryName = "Drama"
                        },
                        new
                        {
                            CategoryID = 5,
                            CategoryName = "Documentary"
                        },
                        new
                        {
                            CategoryID = 6,
                            CategoryName = "Animation"
                        });
                });

            modelBuilder.Entity("Mission06_ckearl2.Models.Movie", b =>
                {
                    b.Property<int>("MovieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MovieID");

                    b.HasIndex("CategoryID");

                    b.ToTable("movies");

                    b.HasData(
                        new
                        {
                            MovieID = 1,
                            CategoryID = 1,
                            Edited = false,
                            LentTo = "-",
                            Notes = "This movie is based in Chicago",
                            Rating = "PG-13",
                            Title = "Ferris Bueller's Day Off"
                        },
                        new
                        {
                            MovieID = 2,
                            CategoryID = 1,
                            Edited = false,
                            LentTo = "-",
                            Notes = "Jack Black is my hero",
                            Rating = "PG-13",
                            Title = "School of Rock"
                        },
                        new
                        {
                            MovieID = 3,
                            CategoryID = 1,
                            Edited = false,
                            LentTo = "Scotty Smalls",
                            Notes = "A cult classic",
                            Rating = "PG",
                            Title = "The Sandlot"
                        },
                        new
                        {
                            MovieID = 4,
                            CategoryID = 4,
                            Edited = true,
                            LentTo = "J.K. Simmons",
                            Notes = "GOAT movie",
                            Rating = "R",
                            Title = "Whiplash"
                        },
                        new
                        {
                            MovieID = 5,
                            CategoryID = 4,
                            Edited = true,
                            LentTo = "Matt Damon",
                            Notes = "The most stacked cast of all time",
                            Rating = "R",
                            Title = "Good Will Hunting"
                        });
                });

            modelBuilder.Entity("Mission06_ckearl2.Models.Movie", b =>
                {
                    b.HasOne("Mission06_ckearl2.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
